

export const scholarshipsByCountry = {
  australia: [
    {
      id: "aus-australia-awards",
      name: "Australia Awards Scholarships",
      level: ["masters", "phd"],
      award: "Full tuition, return airfare, establishment allowance, living stipend (AAS).",
      deadline: null, 
      website: "https://australiaawards.com.au/",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Australia_Awards_logo.svg/512px-Australia_Awards_logo.svg.png",
      countryName: "Australia",
      countrySlug: "australia",
      lastUpdated: "2025-09-15",
    },
    {
      id: "aus-dst-international",
      name: "Destination Australia Scholarships",
      level: ["bachelors", "masters", "phd"],
      award: "Up to AUD 15,000–$30,000 per year to study in regional Australia.",
      deadline: null,
      website: "https://internationaleducation.gov.au/news/latest-news/Pages/Destination-Australia.aspx",
      logo: null,
      countryName: "Australia",
      countrySlug: "australia",
      lastUpdated: "2025-09-15",
    },
    {
      id: "aus-unimelb-graduate-research",
      name: "University of Melbourne Graduate Research Scholarships",
      level: ["masters", "phd"],
      award: "Tuition fee offset, stipend, relocation grant, OSHC.",
      deadline: null,
      website: "https://scholarships.unimelb.edu.au/awards/graduate-research-scholarships",
      logo: null,
      countryName: "Australia",
      countrySlug: "australia",
      lastUpdated: "2025-09-15",
    },
    {
      id: "aus-unsw-international",
      name: "UNSW International Scholarships",
      level: ["bachelors", "masters"],
      award: "Partial to full tuition scholarships for high-achieving students.",
      deadline: null,
      website: "https://www.unsw.edu.au/study/your-future/international-scholarships",
      logo: null,
      countryName: "Australia",
      countrySlug: "australia",
      lastUpdated: "2025-09-15",
    },
  ],

  canada: [
    {
      id: "ca-vanier-cgs",
      name: "Vanier Canada Graduate Scholarships",
      level: ["phd"],
      award: "CAD 50,000 per year for 3 years.",
      deadline: null,
      website: "https://vanier.gc.ca/en/home-accueil.html",
      logo: null,
      countryName: "Canada",
      countrySlug: "canada",
      lastUpdated: "2025-09-15",
    },
    {
      id: "ca-banting-postdoctoral",
      name: "Banting Postdoctoral Fellowships",
      level: ["phd"],
      award: "CAD 70,000 per year for 2 years (postdoc).",
      deadline: null,
      website: "https://banting.fellowships-bourses.gc.ca/",
      logo: null,
      countryName: "Canada",
      countrySlug: "canada",
      lastUpdated: "2025-09-15",
    },
    {
      id: "ca-lester-b-pearson",
      name: "U of T Lester B. Pearson Scholarship",
      level: ["bachelors"],
      award: "Full tuition, books, incidental fees, residence (4 years).",
      deadline: null,
      website: "https://future.utoronto.ca/pearson/",
      logo: null,
      countryName: "Canada",
      countrySlug: "canada",
      lastUpdated: "2025-09-15",
    },
    {
      id: "ca-ubc-oge",
      name: "UBC Outstanding International Student/IMES",
      level: ["bachelors"],
      award: "Merit-based tuition awards; amounts vary.",
      deadline: null,
      website: "https://you.ubc.ca/financial-planning/scholarships-awards-international-students/",
      logo: null,
      countryName: "Canada",
      countrySlug: "canada",
      lastUpdated: "2025-09-15",
    },
  ],

  germany: [
    {
      id: "de-daad-stipendium",
      name: "DAAD Scholarships (various programmes)",
      level: ["bachelors", "masters", "phd"],
      award: "Monthly stipend, travel allowance, insurance; programme-specific.",
      deadline: null,
      website: "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
      logo: "https://www.daad.de/typo3conf/ext/daad_common/Resources/Public/Images/DAAD_logo.svg",
      countryName: "Germany",
      countrySlug: "germany",
      lastUpdated: "2025-09-15",
    },
    {
      id: "de-kas",
      name: "Konrad-Adenauer-Stiftung Scholarships",
      level: ["masters", "phd"],
      award: "Monthly stipend, network, seminars; for international students.",
      deadline: null,
      website: "https://www.kas.de/en/web/begabtenfoerderung-und-kultur",
      logo: null,
      countryName: "Germany",
      countrySlug: "germany",
      lastUpdated: "2025-09-15",
    },
    {
      id: "de-friedrich-ebert",
      name: "Friedrich-Ebert-Stiftung Scholarships",
      level: ["bachelors", "masters", "phd"],
      award: "Monthly stipend; social engagement emphasis.",
      deadline: null,
      website: "https://www.fes.de/studienfoerderung",
      logo: null,
      countryName: "Germany",
      countrySlug: "germany",
      lastUpdated: "2025-09-15",
    },
    {
      id: "de-htw-berlin",
      name: "HTW Berlin Scholarships (examples)",
      level: ["bachelors", "masters"],
      award: "Partial/need-based awards (examples).",
      deadline: null,
      website: "https://www.htw-berlin.de/en/studies/organising-your-studies/financing/scholarships/",
      logo: null,
      countryName: "Germany",
      countrySlug: "germany",
      lastUpdated: "2025-09-15",
    },
  ],

  brazil: [
  {
    id: "br-pec-g-undergraduate",
    name: "Programa de Estudantes-Convênio de Graduação (PEC-G)",
    level: ["bachelors"],
    award: "Full tuition waiver for undergraduate programmes in Brazil; support for Portuguese language preparation via PEC-PLE if needed.", 
    deadline: "2025-07-25", 
    website: "https://www.gov.br/mre/en/subjects/culture-and-education/educational-themes/study-opportunities-for-international-applicants/pec-g", 
    logo: null,
    countryName: "Brazil",
    countrySlug: "brazil",
    lastUpdated: "2025-08-25", 
  },
  {
    id: "br-pec-pg-postgraduate",
    name: "Programa de Estudantes-Convênio de Pós-Graduação (PEC-PG)",
    level: ["masters", "phd"],
    award: "Fully funded Master’s or Doctoral programmes; includes stipend, possibly travel/airfare;  sandwich doctoral options.", 
    deadline: "2025-09-29",  // for full Masters/Doctoral programmes in current (2025-2026) call :contentReference[oaicite:1]{index=1}
    website: "https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/bolsas/bolsas-e-auxilios-internacionais/encontre-aqui/paises/multinacional/programa-de-estudantes-convenio-de-pos-graduacao-pec-pg", 
    logo: null,
    countryName: "Brazil",
    countrySlug: "brazil",
    lastUpdated: "2025-09-01",
  },
  {
    id: "br-oas-gcub-paec",
    name: "OAS-GCUB PAEC Brazil Scholarships",
    level: ["masters", "phd"],
    award: "Full tuition waiver; partial monthly stipend; one-time arrival grant; Portuguese language support.", 
    deadline: null,  // varies each edition; update when known :contentReference[oaicite:2]{index=2}
    website: "https://www.oas.org/en/scholarships/brazil.asp",
    logo: null,
    countryName: "Brazil",
    countrySlug: "brazil",
    lastUpdated: "2025-08-20",
  },
  {
    id: "br-gcub-international-mobility",
    name: "GCUB International Mobility Program (Brazil)",
    level: ["masters", "phd"],
    award: "Master’s/PhD scholarships across many Brazilian universities; covers tuition, fees, stipend, access to university facilities.", 
    deadline: "2025-07-13",  // for 2026 edition as per source :contentReference[oaicite:3]{index=3}
    website: "https://gcub.org.br", 
    logo: null,
    countryName: "Brazil",
    countrySlug: "brazil",
    lastUpdated: "2025-06-07",
  }
  // Could add one more when more verified options are found
],

argentina: [
  {
    id: "ar-uba-scholarship",
    name: "University of Buenos Aires (UBA) Scholarships",
    level: ["bachelors", "masters", "phd"],
    award: "Full or partial tuition fee waiver; support for accommodation or academic materials in some cases.", 
    deadline: "2025-05-31", 
    website: "https://www.uba.ar", 
    logo: null,
    countryName: "Argentina",
    countrySlug: "argentina",
    lastUpdated: "2025-05-15",
  },
  {
    id: "ar-unc-scholarship",
    name: "National University of Córdoba (UNC) Scholarships",
    level: ["bachelors", "masters", "phd"],
    award: "Partial or full exemption of tuition; sometimes monthly stipend; access to housing at university residences for international students.", 
    deadline: "2025-06-30",
    website: "https://www.unc.edu.ar",
    logo: null,
    countryName: "Argentina",
    countrySlug: "argentina",
    lastUpdated: "2025-05-20",
  },
  {
    id: "ar-banco-santander",
    name: "Banco Santander Scholarships (Argentina)",
    level: ["bachelors", "masters", "short-courses"],
    award: "Support for tuition fees, transportation, and in some programmes monthly or one-time financial support.", 
    deadline: "2025-03-31",  // approximate (March) from descriptions :contentReference[oaicite:6]{index=6}
    website: "https://www.bancosantander.com.ar", 
    logo: null,
    countryName: "Argentina",
    countrySlug: "argentina",
    lastUpdated: "2025-04-01",
  },
  {
    id: "ar-mente-argentina",
    name: "Mente Argentina Scholarships",
    level: ["masters", "phd"],
    award: "Partial international scholarships; focus on improving academic/professional skills; may include funding for materials, tuition or part stipend depending on programme.", 
    deadline: "2025-xx-yy",  // need update / varies by programme :contentReference[oaicite:7]{index=7}
    website: "https://www.menteargentina.com", 
    logo: null,
    countryName: "Argentina",
    countrySlug: "argentina",
    lastUpdated: "2025-06-01",
  }
],

china: [
  {
    id: "cn-csc-chinese-government",
    name: "China Scholarship Council (CSC) Government Scholarship",
    level: ["bachelors", "masters", "phd"],
    award: "Full or partial scholarship (tuition, accommodation, monthly stipend, medical insurance) for study in Chinese universities under CSC-affiliated programmes.",  
    deadline: "around February 2025 (varies by university & program)",  
    website: "https://www.chinesescholarshipcouncil.com/",  
    logo: null,
    countryName: "China",
    countrySlug: "china",
    lastUpdated: "2025-01-03",  
  },
  {
    id: "cn-silkroad-program-typeB",
    name: "Chinese Government Scholarship - ‘Silk Road’ Program (Category B)",
    level: ["masters", "phd"],
    award: "Full scholarship including tuition, accommodation, living allowance and medical insurance under CSC-Silk Road scheme.",  
    deadline: "May 20, 2025",  
    website: "https://international.swufe.edu.cn/info/1131/1635.htm",  
    logo: null,
    countryName: "China",
    countrySlug: "china",
    lastUpdated: "2025-04-01",  
  },
  {
    id: "cn-thucg-cs-thucg-typeB-tsinghua",
    name: "Tsinghua University CGS (Type B) Scholarships",
    level: ["masters", "phd"],
    award: "Full CGS: tuition, dorm/subsidised accommodation, stipend, medical insurance. (Partial CGS includes subsets of these.)",  
    deadline: null,  
    website: "https://yz.tsinghua.edu.cn/en/info/1027/1117.htm",  
    logo: null,
    countryName: "China",
    countrySlug: "china",
    lastUpdated: "2025-09-01",  
  }
],

colombia: [
  {
    id: "co-beca-colombia-foreigners-2025-masters",
    name: "Beca Colombia Scholarship Programme for Foreigners (ICETEX) 2025",
    level: ["masters"],
    award: "Full tuition coverage; health/medical insurance; monthly stipend (equivalent to three minimum wages); visa support; courtesy visa letter from ICETEX.",  
    deadline: "June 13, 2025",  
    website: "https://web.icetex.gov.co/becas/beca-colombia-extranjeros",  
    logo: null,
    countryName: "Colombia",
    countrySlug: "colombia",
    lastUpdated: "2025-05-01",  
  },
  {
    id: "co-colfuturo-ihe-delft-master",
    name: "COLFUTURO & IHE Delft Scholarships for Colombian Students",
    level: ["masters"],
    award: "Funding for MSc in Water and Sustainable Development (IHE Delft) for Colombian nationals; joint loan-scholarship model via COLFUTURO & ICETEX. Covers tuition, living costs. ",  
    deadline: "February 28, 2025",  
    website: "https://www.un-ihe.org/education/master-programmes/colfuturo-and-icetex-scholarships-available-colombians",  
    logo: null,
    countryName: "Colombia",
    countrySlug: "colombia",
    lastUpdated: "2025-02-01",  
  }
],

czechrepublic: [
  {
    id: "cz-government-scholarship-foreign-development",
    name: "Government Scholarships of the Czech Republic (Foreign Development Cooperation)",
    level: ["bachelors", "masters", "phd"],
    award: "Tuition waiver at public Czech universities + support for study in Czech or English, including possible preparatory or language course coverage, for applicants from developing countries.",
    website: "https://msmt.gov.cz/eu-and-international-affairs/government-scholarships-developing-countries",  
    logo: null,
    countryName: "Czech Republic",
    countrySlug: "czech-republic",
    lastUpdated: "2025-09-15",
  },
  {
    id: "cz-university-scholarships",
    name: "University / Faculty Scholarships (Czech Universities)",
    level: ["bachelors", "masters", "phd"],
    award: "Various merit-based scholarships or grants offered by Czech universities/faculties for outstanding students, for research, development projects, or artistic work; may include living cost support.",
    website: "https://www.czechuniversities.com/article/scholarships-for-international-students",  
    logo: null,
    countryName: "Czech Republic",
    countrySlug: "czech-republic",
    lastUpdated: "2025-09-15",
  },
  {
    id: "cz-south-moravian-centre-mobility",
    name: "South Moravian Centre for International Mobility Scholarships",
    level: ["masters", "phd"],
    award: "Support for talented international students and researchers (non-EU) at universities in Brno, including Czech- or English-taught programmes.",
    website: "https://www.studyin.cz/plan-your-studies/scholarships/",  
    logo: null,
    countryName: "Czech Republic",
    countrySlug: "czech-republic",
    lastUpdated: "2025-09-15",
  },
  {
    id: "cz-bilateral-exchange-programmes",
    name: "Bilateral & Multilateral Exchange Scholarships (from Czech MEYS)",
    level: ["masters", "phd"],
    award: "Scholarships under government bilateral agreements or exchange programmes arranged via Czech ministry of education or foreign affairs; for study or research stays at public universities.",
    website: "https://msmt.gov.cz/eu-and-international-affairs/scholarships-for-the-academic-year-2025-2026",  
    logo: null,
    countryName: "Czech Republic",
    countrySlug: "czech-republic",
    lastUpdated: "2025-09-15",
  },
],

estonia: [
  {
    id: "ee-government-scholarships",
    name: "Estonian Government Scholarships for International Students & Researchers",
    level: ["bachelors", "masters", "phd", "research"],
    award: "Funding for full degree, short-course, researcher mobility; includes tuition or living/stipend support, sometimes research grants; administered by Education and Youth Board.",
    website: "https://studyinestonia.ee/study/scholarships",  
    logo: null,
    countryName: "Estonia",
    countrySlug: "estonia",
    lastUpdated: "2025-09-15",
  },
  {
    id: "ee-university-tuition-fee-scholarships",
    name: "University of Tartu & Other Estonian Universities Tuition-Fee Scholarships",
    level: ["masters", "phd"],
    award: "Partial or full tuition fee waivers for international students, particularly non-EU or for English-taught programmes.",
    website: "https://studyinestonia.ee/study/scholarships",  
    logo: null,
    countryName: "Estonia",
    countrySlug: "estonia",
    lastUpdated: "2025-09-15",
  },
  {
    id: "ee-estophilus-research‐grants",
    name: "Estophilus Research Grants (Estonia-specific)",
    level: ["research", "phd"],
    award: "Grants for international researchers / PhD candidates for Estonia-related research topics; often short-term funding or fieldworks.",
    website: "https://studyinestonia.ee/study/scholarships",  
    logo: null,
    countryName: "Estonia",
    countrySlug: "estonia",
    lastUpdated: "2025-09-15",
  },
  {
    id: "ee-university-mobility-/semester-exchange",
    name: "Scholarships / Grants for Exchange / Short-Term Study in Estonia",
    level: ["bachelors", "masters"],
    award: "Support for semester exchange, summer/winter schools, mobility programmes via Estonian universities or state agencies, sometimes via Erasmus+.",
    website: "https://studyinestonia.ee/study/scholarships",  
    logo: null,
    countryName: "Estonia",
    countrySlug: "estonia",
    lastUpdated: "2025-09-15",
  },
],

egypt: [
  {
    id: "eg-egyaid-government-scholarships",
    name: "EGYAID Scholarships (Egyptian Government for International Students)",
    level: ["masters", "phd"],
    award: "Tuition fee support for international postgraduate students at Egyptian universities; scholarship program under Egypt’s Ministry of Higher Education.",
    website: "https://admission.study-in-egypt.gov.eg",  
    logo: null,
    countryName: "Egypt",
    countrySlug: "egypt",
    lastUpdated: "2025-09-15",
  },
  {
    id: "eg-AUC-excellence-scholarship",
    name: "AUC Excellence Scholarship Program",
    level: ["bachelors", "masters"],
    award: "Highly competitive merit-based scholarship at the American University in Cairo; percentages of tuition coverage up to full, depending on academic, talent, community service achievements.",
    website: "https://www.aucegypt.edu/admissions/scholarships",  
    logo: null,
    countryName: "Egypt",
    countrySlug: "egypt",
    lastUpdated: "2025-09-15",
  },
  {
    id: "eg-public-universities-internationality",
    name: "Scholarships / Awards at Egyptian Public Universities for Foreign Students",
    level: ["bachelors", "masters"],
    award: "Tuition exemptions, sometimes fee waivers and assistance via university programmes or government-partnered schemes to attract international students.",
    website: "https://education.gov.eg",  
    logo: null,
    countryName: "Egypt",
    countrySlug: "egypt",
    lastUpdated: "2025-09-15",
  },
  {
    id: "eg-sawiris-foundation-aid",
    name: "Sawiris Foundation Scholarships / Grants",
    level: ["bachelors", "masters"],
    award: "Grants and scholarships in various fields via the Sawiris Foundation for Egyptian students; sometimes partnering with international universities and institutions.",
    website: "https://www.sawirisfoundation.org",  
    logo: null,
    countryName: "Egypt",
    countrySlug: "egypt",
    lastUpdated: "2025-09-15",
  },
],

finland: [
  {
    id: "fi-government-scholarships",
    name: "Finnish Government Scholarships for International Students (non-EU/EEA)",
    level: ["masters", "phd"],
    award: "Tuition fee waivers / grants for non-EU/EEA students; support for living expenses depending on university.",
    website: "https://studyinfinland.fi/funding-your-studies/bachelors-and-masters-scholarships",  
    logo: null,
    countryName: "Finland",
    countrySlug: "finland",
    lastUpdated: "2025-09-15",
  },
  {
    id: "fi-university-specific-scholarships",
    name: "Scholarships by Finnish Universities & Universities of Applied Sciences for non-EU/EEA Students",
    level: ["bachelors", "masters"],
    award: "Merit-based scholarships, often covering tuition, sometimes living stipends, offered by individual universities for English-taught programmes.",
    website: "https://studyinfinland.fi/funding-your-studies/bachelors-and-masters-scholarships",  
    logo: null,
    countryName: "Finland",
    countrySlug: "finland",
    lastUpdated: "2025-09-15",
  },
  {
    id: "fi-edufin-master-research-grants",
    name: "Research Grants for Graduate Students in Finland",
    level: ["masters", "phd"],
    award: "Research grants, scholarships for graduate students, especially in technical, science and engineering fields via Finnish research universities.",
    website: "https://studyinfinland.fi",  
    logo: null,
    countryName: "Finland",
    countrySlug: "finland",
    lastUpdated: "2025-09-15",
  },
  {
    id: "fi-summer-/winter-school-scholarships",
    name: "Short-term / Exchange & Seasonal Program Scholarships in Finland",
    level: ["bachelors", "masters"],
    award: "Support for students participating in summer / winter schools, exchange semesters / mobility programmes, often via Erasmus+ or university partners.",
    website: "https://studyinfinland.fi",  
    logo: null,
    countryName: "Finland",
    countrySlug: "finland",
    lastUpdated: "2025-09-15",
  },
],

fiji: [
  {
    id: "fj-australia-awards",
    name: "Australia Awards Fiji",
    level: ["bachelors", "masters"],
    award: "Full or partial scholarships to study in Australia or Pacific institutions; includes tuition, travel and living allowances as per Australia Awards scheme.",
    website: "https://australiaawardsfiji.org/",
    logo: null,
    countryName: "Fiji",
    countrySlug: "fiji",
    lastUpdated: "2025-09-15",
  },
  {
    id: "fj-aaps-pacific",
    name: "Australia Awards Pacific Scholarships (AAPS)",
    level: ["bachelors", "masters"],
    award: "Scholarships for people from Pacific developing countries to study at tertiary institutions in the Pacific or Australia; covers tuition, travel, allowances.",
    website: "https://www.dfat.gov.au/people-to-people/australia-awards/australia-awards-pacific-scholarships-aaps",
    logo: null,
    countryName: "Fiji",
    countrySlug: "fiji",
    lastUpdated: "2025-09-15",
  },
  {
    id: "fj-national-toppers-overseas",
    name: "Fiji National Toppers Scheme Overseas Scholarships",
    level: ["bachelors"],
    award: "Scholarships by Fiji’s Tertiary Scholarships & Loans Board for top ranked students to study abroad in priority areas; covers tuition and allowances.",
    website: "https://science.anu.edu.au/study/scholarships/fiji-national-toppers-scheme-overseas-scholarships",
    logo: null,
    countryName: "Fiji",
    countrySlug: "fiji",
    lastUpdated: "2025-09-15",
  },
],

france: [
  {
    id: "fr-eiffel-excellence",
    name: "Eiffel Excellence Scholarship Program",
    level: ["masters", "phd"],
    award: "Scholarships by French Ministry for highly ranked foreign students; monthly stipend, possible travel & health support; for Master's & Doctoral studies.",
    website: "https://www.campusfrance.org/en/bursaries-foreign-students",  // the general France foreign student bursary page including Eiffel info :contentReference[oaicite:0]{index=0}
    logo: null,
    countryName: "France",
    countrySlug: "france",
    lastUpdated: "2025-09-15",
  },
  {
    id: "fr-foreign-ministry-scholarships",
    name: "French Foreign Ministry Scholarships",
    level: ["bachelors", "masters", "phd"],
    award: "Scholarships financed by the French government & embassies abroad including Major programmes for top foreign students and grants for foreign high potential students.",
    website: "https://www.campusfrance.org/en/bursaries-foreign-students",
    logo: null,
    countryName: "France",
    countrySlug: "france",
    lastUpdated: "2025-09-15",
  },
  {
    id: "fr-campus-bourses",
    name: "Campus Bourses (Scholarship Tool for Foreign Students in France)",
    level: ["all levels"],
    award: "A service/portal listing many types of assistance (scholarships, grants) from foundations/regions/universities to foreign students to help with tuition, cost of living, etc.",
    website: "https://www.campusfrance.org/en/bursaries-foreign-students",
    logo: null,
    countryName: "France",
    countrySlug: "france",
    lastUpdated: "2025-09-15",
  },
  {
    id: "fr-excellence-europa",
    name: "France Excellence Europa Scholarship Programme",
    level: ["masters"],
    award: "Scholarships for European students to pursue Master’s level studies in France; includes allowances and assistance via French Higher Education Ministry programmes. ",
    website: "https://www.campusfrance.org/en/actu/france-excellence-europa-scholarship-applications",
    logo: null,
    countryName: "France",
    countrySlug: "france",
    lastUpdated: "2025-09-15",
  },
],

germany: [
  {
    id: "de-daad",
    name: "DAAD Scholarships",
    level: ["masters", "phd", "research stays"],
    award: "Wide range of scholarships by the German Academic Exchange Service; many for international postgraduates & researchers; includes stipend, travel support, university fees where applicable. ",
    website: "https://www.daad.de/en/studying-in-germany/scholarships/",  
    logo: null,
    countryName: "Germany",
    countrySlug: "germany",
    lastUpdated: "2025-09-15",
  },
  {
    id: "de-studienstiftung",
    name: "Studienstiftung des deutschen Volkes (German Academic Scholarship Foundation)",
    level: ["bachelors", "masters", "phd"],
    award: "One of Germany's most prestigious merit-based scholarships; supports talented students academically, financially, with mentoring etc.",
    website: "https://www.studienstiftung.de/",  
    logo: null,
    countryName: "Germany",
    countrySlug: "germany",
    lastUpdated: "2025-09-15",
  },
  {
    id: "de-daad-doctoral-programs",
    name: "DAAD Doctoral Programmes Scholarships",
    level: ["phd"],
    award: "DAAD support specific for PhD research & doctoral studies; includes stipend, possibly travel, bonus etc.",
    website: "https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/",  
    logo: null,
    countryName: "Germany",
    countrySlug: "germany",
    lastUpdated: "2025-09-15",
  },
  {
    id: "de-daad-artists-in-berlin",
    name: "DAAD Artists-in-Berlin Program",
    level: ["research", "artists"],
    award: "Fellowship for artists from all countries to spend a year in Berlin, working on their art, with stipend, accommodation etc.",
    website: "https://www.berliner-kuenstlerprogramm.de/",  
    logo: null,
    countryName: "Germany",
    countrySlug: "germany",
    lastUpdated: "2025-09-15",
  },
],

hungary: [
  {
    id: "hu-stipendium-hungaricum",
    name: "Stipendium Hungaricum Scholarship Programme",
    level: ["bachelors", "masters", "phd"],
    award: "Fully funded scholarships by the Hungarian government for international students; covers tuition, stipend, accommodation depending on programme.",
    website: "https://stipendiumhungaricum.hu/",  
    logo: null,
    countryName: "Hungary",
    countrySlug: "hungary",
    lastUpdated: "2025-09-15",
  },
  {
    id: "hu-european-union-erasmus",
    name: "Erasmus+ Scholarships (EU / Hungarian participation)",
    level: ["masters", "exchange", "short-term research"],
    award: "Scholarships/grants through Erasmus+ for students from partner countries to study or do research in Hungary / or Hungarian students abroad.",
    website: "https://stipendiumhungaricum.hu/",  
    logo: null,
    countryName: "Hungary",
    countrySlug: "hungary",
    lastUpdated: "2025-09-15",
  },
  {
    id: "hu-university-merit-programs",
    name: "Hungarian Universities Merit / Excellence Scholarships",
    level: ["bachelors", "masters", "phd"],
    award: "Merit-based scholarships offered by Hungarian universities to international students especially for English-taught programmes; often tuition waivers + partial stipends.",
    website: "https://stipendiumhungaricum.hu/",  
    logo: null,
    countryName: "Hungary",
    countrySlug: "hungary",
    lastUpdated: "2025-09-15",
  },
],

india: [
  {
    id: "in-pmrf",
    name: "Prime Minister's Research Fellowship (PMRF)",
    level: ["phd"],
    award: "One of India’s premier PhD fellowships in science & engineering; high stipend + research grant component; aimed at retaining top talent in research. ",
    website: "https://www.pmrf.in/",  
    logo: null,
    countryName: "India",
    countrySlug: "india",
    lastUpdated: "2025-09-15",
  },
  {
    id: "in-daad-scholarships",
    name: "DAAD Scholarships for Indian Students",
    level: ["masters", "phd"],
    award: "Scholarships by DAAD allowing Indian students to study in Germany for postgraduate / doctoral level; includes stipend, travel & insurance in many cases. ",
    website: "https://www.daad.de/en/studying-in-germany/scholarships/",  
    logo: null,
    countryName: "India",
    countrySlug: "india",
    lastUpdated: "2025-09-15",
  },
  {
    id: "in-ugc-net-jrf-sr-fellowship",
    name: "UGC NET / Junior Research / Senior Research Fellowships",
    level: ["masters completing / early phd"],
    award: "Indian government fellowships for research scholars providing stipend, contingency grants, for those qualified through UGC-NET exams or similar eligibility tests.",
    website: "https://www.indiascienceandtechnology.gov.in/fellowships-scholarships",  
    logo: null,
    countryName: "India",
    countrySlug: "india",
    lastUpdated: "2025-09-15",
  },
  {
    id: "in-inspire-fellowship",
    name: "INSPIRE Fellowship / Scholarship Programmes",
    level: ["bachelors", "masters"],
    award: "Science & technology fellowships by Government of India to encourage research / talent early, support students in basic/applied sciences with stipend / awards / research exposure.",
    website: "https://www.indiascienceandtechnology.gov.in/fellowships-scholarships",  
    logo: null,
    countryName: "India",
    countrySlug: "india",
    lastUpdated: "2025-09-15",
  }
],

italy: [
  {
    id: "it-maeci-study-in-italy",
    name: "Italian Government (MAECI) Study in Italy Scholarships",
    level: ["bachelors", "masters", "phd"],
    award: "Grants from the Italian Ministry of Foreign Affairs and International Cooperation to support international students with tuition and living allowances in Italy.",  
    website: "https://studyinitaly.esteri.it/borse/study-in-italy/en/",  
    logo: null,
    countryName: "Italy",
    countrySlug: "italy",
    lastUpdated: "2025-09-15",
  },
  {
    id: "it-invest-your-talent",
    name: "Invest Your Talent in Italy",
    level: ["masters"],
    award: "Scholarships for international students enrolling in selected English-taught Master’s programmes in fields such as engineering, economics and management at Italian universities.",  
    website: "https://investyourtalentapplication.esteri.it/SitoIYT/EN/invest-your-talent-in-italy",  
    logo: null,
    countryName: "Italy",
    countrySlug: "italy",
    lastUpdated: "2025-09-15",
  },
  {
    id: "it-unimi-excellence",
    name: "University of Milan International Excellence Scholarships",
    level: ["masters"],
    award: "Incentives and tuition fee waivers offered to international students admitted to Master’s degree programs at the University of Milan.",  
    website: "https://www.unimi.it/en/study/financial-support/international-scholarships",  
    logo: null,
    countryName: "Italy",
    countrySlug: "italy",
    lastUpdated: "2025-09-15",
  },
  {
    id: "it-unibo-international-talents",
    name: "Unibo International Talents Scholarships",
    level: ["masters"],
    award: "Merit-based scholarships that exempt tuition fees and provide financial incentives for international students enrolling in Bologna’s Master’s programs.",  
    website: "https://www.unibo.it/en/study/study-grants-and-subsidies/international-talents-unibo-scholarships-for-international-students",  
    logo: null,
    countryName: "Italy",
    countrySlug: "italy",
    lastUpdated: "2025-09-15",
  },
],

japan: [
  {
    id: "jp-mext-scholarship",
    name: "MEXT Japanese Government Scholarship",
    level: ["bachelors", "masters", "phd"],
    award: "Fully funded scholarships administered by Japan’s Ministry of Education, Culture, Sports, Science and Technology (MEXT) for international students to study at Japanese universities.",  
    website: "https://www.studyinjapan.go.jp/en/smap-stopj-applications-mext.html",  
    logo: null,
    countryName: "Japan",
    countrySlug: "japan",
    lastUpdated: "2025-09-15",
  },
  {
    id: "jp-jasso-scholarship",
    name: "JASSO Study in Japan Scholarship",
    level: ["bachelors", "masters", "exchange"],
    award: "Monthly stipend scholarships by Japan Student Services Organization (JASSO) for international students enrolled in university or exchange programs in Japan.",  
    website: "https://www.jasso.go.jp/en/study_j/scholarship.html",  
    logo: null,
    countryName: "Japan",
    countrySlug: "japan",
    lastUpdated: "2025-09-15",
  },
  {
    id: "jp-university-specific-scholarships",
    name: "University-Specific International Scholarships in Japan",
    level: ["bachelors", "masters", "phd"],
    award: "Merit-based scholarships and tuition waivers offered by Japanese universities (e.g. University of Tokyo, Kyoto University) for incoming international students.",  
    website: "https://www.studyinjapan.go.jp/en/plan/scholarships.html",  
    logo: null,
    countryName: "Japan",
    countrySlug: "japan",
    lastUpdated: "2025-09-15",
  },
  {
    id: "jp-jica-scholarship",
    name: "JICA Youth Exchange Scholarship",
    level: ["masters"],
    award: "Scholarships from the Japan International Cooperation Agency (JICA) supporting international students from partner countries for Master’s level studies in Japan and exchange programs.",  
    website: "https://www.jica.go.jp/english/countries/asia/topics/yu_20220210.html",  
    logo: null,
    countryName: "Japan",
    countrySlug: "japan",
    lastUpdated: "2025-09-15",
  },
],

kenya: [
  {
    id: "ke-maasai-marathon-scholarship",
    name: "Maasai Women Development Organization Scholarships",
    level: ["bachelors", "masters"],
    award: "Scholarships and grants provided to Maasai and rural Kenyan girls to support their higher education, including tuition support and mentorship programs.",  
    website: "https://maasai-women.org",  
    logo: null,
    countryName: "Kenya",
    countrySlug: "kenya",
    lastUpdated: "2025-09-15",
  },
  {
    id: "ke-university-of-nairobi-international",
    name: "University of Nairobi International Student Scholarships",
    level: ["bachelors", "masters", "phd"],
    award: "Partial tuition waivers or merit-based scholarships for international students enrolling at University of Nairobi undergraduate and postgraduate programs.",  
    website: "https://uonbi.ac.ke",  
    logo: null,
    countryName: "Kenya",
    countrySlug: "kenya",
    lastUpdated: "2025-09-15",
  },
  {
    id: "ke-ipdet-nairobi",
    name: "International Program for Development Evaluation Training (IPDET) Scholarships (Nairobi)",
    level: ["masters", "professional", "research"],
    award: "Scholarships to attend the IPDET On-Site Program in Nairobi, covering training materials and programme fees for development evaluation professionals. ",  
    website: "https://ipdet.org",  
    logo: null,
    countryName: "Kenya",
    countrySlug: "kenya",
    lastUpdated: "2025-09-15",
  },
  {
    id: "ke-manchester-global-futures",
    name: "University of Manchester Global Futures Africa Scholarships",
    level: ["masters"],
    award: "Fee discount scholarships for African students, including Kenyan residents, to pursue master’s degrees at the University of Manchester.",  
    website: "https://www.manchester.ac.uk/study/international/country-specific-information/kenya/scholarships/",  
    logo: null,
    countryName: "Kenya",
    countrySlug: "kenya",
    lastUpdated: "2025-09-15",
  },
],

morocco: [
  {
    id: "ma-amci-scholarships",
    name: "Moroccan Agency for International Cooperation (AMCI) Scholarships",
    level: ["bachelors", "masters", "research"],
    award: "Scholarships provided by Morocco’s AMCI to foreign students to study in Morocco, including tuition funding and living allowances in selected universities.",  
    website: "https://www.amci.ma",  
    logo: null,
    countryName: "Morocco",
    countrySlug: "morocco",
    lastUpdated: "2025-09-15",
  },
  {
    id: "ma-morocco-presidential-scholarships",
    name: "Presidential Scholarships of Morocco for Foreign Students",
    level: ["masters", "phd"],
    award: "Scholarships granted to highly qualified foreign postgraduate students for full or partial study in Morocco; emphasis on academic quality and intercultural exchange.",
    website: "https://www.morocco-scholarships.com",  
    logo: null,
    countryName: "Morocco",
    countrySlug: "morocco",
    lastUpdated: "2025-09-15",
  },
  {
    id: "ma-universite-internationale-rabatt",
    name: "Université Internationale de Rabat International Scholarships",
    level: ["bachelors", "masters"],
    award: "Tuition waivers and financial aid for international students at the International University of Rabat, including engineering and applied science programmes.",  
    website: "https://www.uir.ac.ma",  
    logo: null,
    countryName: "Morocco",
    countrySlug: "morocco",
    lastUpdated: "2025-09-15",
  },
  {
    id: "ma-erasmus-morocco",
    name: "Erasmus+ Study/Research Grants Involving Morocco",
    level: ["masters", "exchange"],
    award: "Erasmus+ mobility grants that fund study or research stays in Morocco as part of an exchange programme between Moroccan and partner universities abroad.",  
    website: "https://erasmus-plus.ec.europa.eu/",  
    logo: null,
    countryName: "Morocco",
    countrySlug: "morocco",
    lastUpdated: "2025-09-15",
  },
],

nepal: [
  {
    id: "np-saci-scholarship",
    name: "South Asia Citizens Initiative (SACI) Scholarships",
    level: ["bachelors", "masters"],
    award: "Scholarships for Nepalese students to study in Asian countries under SACI framework, including tuition support and study materials.",  
    website: "https://saci-f.org",  
    logo: null,
    countryName: "Nepal",
    countrySlug: "nepal",
    lastUpdated: "2025-09-15",
  },
  {
    id: "np-mohe-government-scholarships",
    name: "Nepal Ministry of Higher Education Foreign Scholarships",
    level: ["bachelors", "masters", "phd"],
    award: "Scholarships provided by Nepal’s Ministry of Higher Education for Nepalese and international students to study abroad or in Nepal, covering tuition and accommodation in some cases.",  
    website: "https://mohe.gov.np",  
    logo: null,
    countryName: "Nepal",
    countrySlug: "nepal",
    lastUpdated: "2025-09-15",
  },
  {
    id: "np-nul-international",
    name: "Nepal Open University International Student Scholarships",
    level: ["bachelors", "masters"],
    award: "Financial aid or tuition fee discounts offered to international and Nepalese students enrolled in Open University programmes, particularly distance learning and online degrees.",  
    website: "https://nou.edu.np",  
    logo: null,
    countryName: "Nepal",
    countrySlug: "nepal",
    lastUpdated: "2025-09-15",
  },
  {
    id: "np-asia-foundation-scholarship",
    name: "Asia Foundation Nepal Scholarships",
    level: ["masters", "professional"],
    award: "Professional development and study abroad grants from The Asia Foundation for Nepalese students and professionals for training or research in Asia or U.S.",  
    website: "https://asiafoundation.org",  
    logo: null,
    countryName: "Nepal",
    countrySlug: "nepal",
    lastUpdated: "2025-09-15",
  },
],


lithuania: [
  {
    id: "lt-state-scholarships",
    name: "Lithuanian State Scholarships for Master’s & Integrated Studies",
    level: ["masters", "integrated"],
    award: "Scholarships by Education Exchanges Support Foundation covering tuition and stipend support for full-time studies in Lithuania.",  
    website: "https://studyin.lt/scholarships/",  // official “Study in Lithuania” scholarships page :contentReference[oaicite:0]{index=0}  
    logo: null,
    countryName: "Lithuania",
    countrySlug: "lithuania",
    lastUpdated: "2025-09-15",
  },
  {
    id: "lt-vmu-tuition-waiver",
    name: "Vytautas Magnus University English-Taught Programme Fee Waiver",
    level: ["bachelors", "masters"],
    award: "Tuition fee discounts/waivers for applicants to English-taught programmes at VMU; scholarship commission may grant partial or full tuition waivers.",  
    website: "https://www.vdu.lt/en/studies/scholarships/",  // VMU’s scholarships info :contentReference[oaicite:1]{index=1}  
    logo: null,
    countryName: "Lithuania",
    countrySlug: "lithuania",
    lastUpdated: "2025-09-15",
  },
  {
    id: "lt-lithuanian-government-programme",
    name: "Lithuanian Government Scholarships for International Students",
    level: ["bachelors", "masters", "phd"],
    award: "Scholarships offered by government agencies for international students to cover tuition, sometimes stipend or living cost, across various universities.",  
    website: "https://studyin.lt/scholarships/",  
    logo: null,
    countryName: "Lithuania",
    countrySlug: "lithuania",
    lastUpdated: "2025-09-15",
  }
],

malaysia: [
  {
    id: "my-mis",
    name: "Malaysia International Scholarship (MIS)",
    level: ["masters", "phd"],
    award: "Scholarship by Malaysian Government to attract high calibre international postgraduates; includes tuition, monthly stipend, one-time allowances etc.",  
    website: "https://biasiswa.mohe.gov.my/INTER/index.php",  // MIS official page :contentReference[oaicite:2]{index=2}  
    logo: null,
    countryName: "Malaysia",
    countrySlug: "malaysia",
    lastUpdated: "2025-09-15",
  },
  {
    id: "my-mtcp",
    name: "Malaysian Technical Cooperation Programme (MTCP)",
    level: ["masters", "short-term", "undergraduate"],
    award: "Government-funded scholarships for students from developing countries; covers fees, accommodation, living allowance etc.",  
    website: "https://mtcp.kln.gov.my/scholarship",  // MTCP official programme :contentReference[oaicite:3]{index=3}  
    logo: null,
    countryName: "Malaysia",
    countrySlug: "malaysia",
    lastUpdated: "2025-09-15",
  },
  {
    id: "my-albukhary-scholarship",
    name: "Albukhary Scholarship Program",
    level: ["bachelors", "masters"],
    award: "Scholarships offered via Albukhary Foundation, includes academic merit, service excellence awards, leadership; support may include tuition, living expenses, campus residence.",  
    website: "https://www.albukharyfoundation.org",  // Albukhary Foundation info :contentReference[oaicite:4]{index=4}  
    logo: null,
    countryName: "Malaysia",
    countrySlug: "malaysia",
    lastUpdated: "2025-09-15",
  }
],

mexico: [
  {
    id: "mx-amexcid-scholarships",
    name: "AMEXCID Scholarships for Foreign Students in Mexico",
    level: ["bachelors", "masters", "phd", "research"],
    award: "Scholarships by the Mexican Agency for International Development Cooperation offering tuition waivers, monthly support and international student assistance across Mexican institutions.",  
    website: "https://www.gob.mx/amexcid",  // AMEXCID foreign student programme :contentReference[oaicite:5]{index=5}  
    logo: null,
    countryName: "Mexico",
    countrySlug: "mexico",
    lastUpdated: "2025-09-15",
  },
  {
    id: "mx-conacyt-foreign-graduates",
    name: "CONACYT Scholarships for Graduate Studies (Foreign Students)",
    level: ["masters", "phd"],
    award: "Grants via Mexico’s CONACYT for quality graduate programmes (Programa Nacional de Posgrados de Calidad) open to international students in participating universities.",  
    website: "https://www.conacyt.mx",  // CONACYT official site (for graduate programmes & scholarships)  
    logo: null,
    countryName: "Mexico",
    countrySlug: "mexico",
    lastUpdated: "2025-09-15",
  }
],

netherlands: [
  {
    id: "nl-orange-tulip-scholarship",
    name: "Orange Tulip Scholarship Programme",
    level: ["bachelors", "masters"],
    award: "Scholarships managed by Nuffic for international students from Neso countries; often partial tuition waivers or financial support provided by universities partnered with Dutch organisations.",  
    website: "https://www.studyinnl.org/scholarships/orange-tulip-scholarship",  // Orange Tulip official info :contentReference[oaicite:6]{index=6}  
    logo: null,
    countryName: "Netherlands",
    countrySlug: "netherlands",
    lastUpdated: "2025-09-15",
  }
],

newzealand: [
  {
    id: "nz-manaaki-new-zealand",
    name: "Manaaki New Zealand Scholarships",
    level: ["bachelors", "masters", "short-term training"],
    award: "Government of New Zealand scholarships for partner countries; covers tuition, allowances, and offers supporting opportunities in study, training or English language programmes.",  
    website: "https://www.nzscholarships.govt.nz/",  // Manaaki NZ official :contentReference[oaicite:7]{index=7}  
    logo: null,
    countryName: "New Zealand",
    countrySlug: "new-zealand",
    lastUpdated: "2025-09-15",
  },
  {
    id: "nz-excellence-awards",
    name: "New Zealand Excellence Awards",
    level: ["masters", "professional development"],
    award: "Scholarships for international students showcasing excellence; often include tuition fees coverage and support from host institution.",  
    website: "https://www.nzscholarships.govt.nz/",  // part of NZ’s scholarship offerings; NZ Excellence is referenced in some compile lists :contentReference[oaicite:8]{index=8}  
    logo: null,
    countryName: "New Zealand",
    countrySlug: "new-zealand",
    lastUpdated: "2025-09-15",
  }
],

norway: [
  {
    id: "no-bi-presidential-scholarship",
    name: "BI Presidential Scholarship",
    level: ["masters"],
    award: "Full tuition scholarship at BI Norwegian Business School for outstanding international students (non-Norwegian), covering tuition and partial stipend.",  
    website: "https://bi.edu/",
    logo: null,
    countryName: "Norway",
    countrySlug: "norway",
    lastUpdated: "2025-09-15",
  },
  {
    id: "no-noram-scholarship",
    name: "NORAM Scholarship",
    level: ["masters", "exchange"],
    award: "Scholarship by the Norway-America Association for U.S. students to pursue master’s study or exchange in Norway; includes tuition and living support.",  
    website: "https://noram.no/",
    logo: null,
    countryName: "Norway",
    countrySlug: "norway",
    lastUpdated: "2025-09-15",
  },
  {
    id: "no-eea-grants",
    name: "EEA & Norway Grants Programmes",
    level: ["research", "masters", "project-based"],
    award: "Funding via EEA & Norway Grants for projects, research and collaborations across Europe or in beneficiary states; used for both institutional grants and scholarships.",  
    website: "https://eeagrants.org/",
    logo: null,
    countryName: "Norway",
    countrySlug: "norway",
    lastUpdated: "2025-09-15",
  }
],

poland: [
  {
    id: "pl-polish-government-scholarships",
    name: "Polish Government Scholarship Programme for Foreign Students (Ministry of Education)",
    level: ["bachelors", "masters", "phd"],
    award: "Scholarships for international students to study in Poland in public higher education institutions; includes tuition support, sometimes stipend or housing subsidy.",  
    website: "https://www.gov.pl/web/nauka/international-cooperation",  // Polish government / national portal  
    logo: null,
    countryName: "Poland",
    countrySlug: "poland",
    lastUpdated: "2025-09-15",
  }
],

portugal: [
  {
    id: "pt-portugal-government-scholarships",
    name: "Portugal Government International Scholarships",
    level: ["bachelors", "masters", "phd"],
    award: "Government-funded scholarships to international students for study at Portuguese higher education institutions; covers tuition and may include stipend or living support.",  
    website: "https://www.dges.gov.pt",
    logo: null,
    countryName: "Portugal",
    countrySlug: "portugal",
    lastUpdated: "2025-09-15",
  },
  {
    id: "pt-universidade-do-porto-scholarships",
    name: "University of Porto Merit & Research Scholarships",
    level: ["bachelors", "masters", "phd"],
    award: "Scholarships by U.Porto for high-academic merit students and for research projects; includes tuition waivers and research funding.",  
    website: "https://www.up.pt/portal/en/live/student-life/scholarships-and-funding/",  
    logo: null,
    countryName: "Portugal",
    countrySlug: "portugal",
    lastUpdated: "2025-09-15",
  },
  {
    id: "pt-camões-language-culture",
    name: "Camões Institute Language & Culture Scholarships",
    level: ["short-course", "masters", "doctoral research"],
    award: "Scholarships to study Portuguese language and culture; also funding for researchers/lecturers or students in Portuguese Studies through Camões, I.P.",  
    website: "https://www.instituto-camoes.pt/",
    logo: null,
    countryName: "Portugal",
    countrySlug: "portugal",
    lastUpdated: "2025-09-15",
  },
  {
    id: "pt-bolsas-santander-apoiouniversitario",
    name: "Santander Universities – Bolsa Apoio Universitário Scholarships",
    level: ["bachelors", "masters"],
    award: "Scholarships by Santander Portugal to support students with financial need, offering cash assistance and sometimes tuition support.",  
    website: "https://www.unl.pt/en/",
    logo: null,
    countryName: "Portugal",
    countrySlug: "portugal",
    lastUpdated: "2025-09-15",
  }
],

qatar: [
  {
    id: "qa-qatar-university-scholarships",
    name: "Qatar University Scholarships for International Students",
    level: ["bachelors", "masters", "phd"],
    award: "Merit-based scholarships offered by Qatar University to international students, including tuition waivers and some support for living and fees.",  
    website: "https://qu.edu.qa/",
    logo: null,
    countryName: "Qatar",
    countrySlug: "qatar",
    lastUpdated: "2025-09-15",
  }
],

ireland: [
  {
    id: "ie-goi-ies",
    name: "Government of Ireland International Education Scholarships (GOI-IES)",
    level: ["masters", "phd"],
    award: "Scholarship by the Irish Government providing fee waiver plus stipend (€10,000) for high-calibre international students to pursue postgraduate studies in Ireland.",  
    website: "https://hea.ie/policy/internationalisation/goi-ies/",  
    logo: null,
    countryName: "Ireland",
    countrySlug: "ireland",
    lastUpdated: "2025-09-15",
  }
],


philippines: [
  {
    id: "ph-fulbright-foreign-student",
    name: "Fulbright Foreign Student Program (Philippines)",
    level: ["masters", "phd"],
    award: "Fully funded or greatly subsidized graduate studies in the USA; tuition, stipend, research & travel support via Fulbright Philippines. ",
    website: "https://fulbright.org.ph/Grants-for-Filipinos",  
    logo: null,
    countryName: "Philippines",
    countrySlug: "philippines",
    lastUpdated: "2025-09-15",
  },
  {
    id: "ph-chevening",
    name: "Chevening Scholarships (UK - Philippines)",
    level: ["masters"],
    award: "Fully funded master’s awards from the UK Foreign & Commonwealth Office for outstanding leaders from the Philippines. ",
    website: "https://www.chevening.org/scholarship/philippines/",  
    logo: null,
    countryName: "Philippines",
    countrySlug: "philippines",
    lastUpdated: "2025-09-15",
  },
  {
    id: "ph-foreign-scholarship-and-training-program",
    name: "Foreign Scholarship and Training Program (FSTP)",
    level: ["bachelors", "masters", "training"],
    award: "Philippine Commission on Higher Education (CHED) programme supporting overseas study & training, funding from foreign donors; includes tuition/training fees etc.",
    website: "https://ieducationphl.ched.gov.ph/fstp/",  
    logo: null,
    countryName: "Philippines",
    countrySlug: "philippines",
    lastUpdated: "2025-09-15",
  },
  {
    id: "ph-ucd-global-scholarship",
    name: "UCD Global Excellence Scholarships for Philippines Students",
    level: ["bachelors", "masters"],
    award: "Scholarships offered by University College Dublin for Philippine students (full or partial awards depending on merit), especially for those who receive offer from UCD.",
    website: "https://www.ucd.ie/global/study-at-ucd/studyatucd‐philippines/scholarshipsfinances/",  
    logo: null,
    countryName: "Philippines",
    countrySlug: "philippines",
    lastUpdated: "2025-09-15",
  }
],

singapore: [
  {
    id: "sg-singa",
    name: "Singapore International Graduate Award (SINGA)",
    level: ["phd"],
    award: "Bond-free PhD or EngD scholarships in science & engineering, offered in collaboration among A*STAR, NUS, NTU, SMU, SUTD, SIT.",
    website: "https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa",  
    logo: null,
    countryName: "Singapore",
    countrySlug: "singapore",
    lastUpdated: "2025-09-15",
  },
  {
    id: "sg-nus-international-undergrad",
    name: "NUS International Undergraduate Scholarship",
    level: ["bachelors"],
    award: "Merit-based scholarships for international students admitted to NUS; often include tuition support & some stipend or living allowance.",
    website: "https://nus.edu.sg/oam/scholarships/scholarships-for-freshmen-%28international-students%29",  
    logo: null,
    countryName: "Singapore",
    countrySlug: "singapore",
    lastUpdated: "2025-09-15",
  },
  {
    id: "sg-asean-scholarship",
    name: "ASEAN Undergraduate Scholarship (Singapore MOE)",
    level: ["secondary", "pre-university", "bachelors"],
    award: "Scholarship by Singapore MOE for students from other ASEAN countries; covers tuition in selected secondary/pre-university schools or universities (depending on scheme).",
    website: "https://www.moe.gov.sg/financial-matters/awards-scholarships/asean-scholarship",  
    logo: null,
    countryName: "Singapore",
    countrySlug: "singapore",
    lastUpdated: "2025-09-15",
  },
  {
    id: "sg-smu-donor-scholarships",
    name: "SMU Donor & Faculty Scholarships (International Students)",
    level: ["bachelors"],
    award: "Scholarships by Singapore Management University via donors/faculties for international undergraduates (some merit + financial need), e.g. Diana Koh International Scholarship, SCIS scholarships etc.",
    website: "https://admissions.smu.edu.sg/scholarships/prospective-students/international-students",  
    logo: null,
    countryName: "Singapore",
    countrySlug: "singapore",
    lastUpdated: "2025-09-15",
  }
],

slovakia: [
  {
    id: "sk-national-scholarship-programme",
    name: "National Scholarship Programme of the Slovak Republic",
    level: ["masters", "phd", "exchange"],
    award: "Government-funded programme supporting international students, researchers, university teachers and artists to undertake stays or research in Slovakia; includes stipend & mobility support. ",
    website: "https://www.scholarships.sk/en/main/programme-terms-and-conditions/foreign-applicants",  
    logo: null,
    countryName: "Slovakia",
    countrySlug: "slovakia",
    lastUpdated: "2025-09-15",
  },
  {
    id: "sk-talent-scholarship-slovakia",
    name: "Scholarships for Talented Students from Abroad (Slovakia)",
    level: ["bachelors", "masters"],
    award: "Scholarships for talented international students worldwide to pursue full-time bachelor’s or master’s studies at Slovak public HEIs; includes annual support amount, tuition waiver in some cases. ",
    website: "https://scholarships.portalvs.sk/",  
    logo: null,
    countryName: "Slovakia",
    countrySlug: "slovakia",
    lastUpdated: "2025-09-15",
  }
],

spain: [
  {
    id: "es-maec-aecid",
    name: "MAEC-AECID Scholarships (Spain)",
    level: ["bachelors", "masters", "phd"],
    award: "Scholarships by the Spanish Ministry of Foreign Affairs and Cooperation for foreign students to study in Spain; covers tuition, travel & living allowances depending on programme. ",
    website: "https://futuresabroad.com/study-in-spain-top-scholarships-for-international-students/",  
    logo: null,
    countryName: "Spain",
    countrySlug: "spain",
    lastUpdated: "2025-09-15",
  },
  {
    id: "es-juan-de-la-cierva",
    name: "Juan de la Cierva Postdoctoral Scholarship (Spain)",
    level: ["postdoc", "research"],
    award: "Prestigious research scholarships for outstanding young researchers to carry out post-doctoral research in Spain, funded by the Spanish Ministry of Science. ",
    website: "https://en.wikipedia.org/wiki/Juan_de_la_Cierva_Scholarship",  
    logo: null,
    countryName: "Spain",
    countrySlug: "spain",
    lastUpdated: "2025-09-15",
  },
  {
    id: "es-ramon-y-cajal",
    name: "Ramón y Cajal Contracts (Spain)",
    level: ["research", "postdoc"],
    award: "Long-term research contracts for outstanding researchers to work in Spanish research institutions; includes salary & research funding. ",
    website: "https://en.wikipedia.org/wiki/Ram%C3%B3n_y_Cajal_%28scholarship%29",  
    logo: null,
    countryName: "Spain",
    countrySlug: "spain",
    lastUpdated: "2025-09-15",
  }
],

papuanewguinea: [
  {
    id: "png-government-scholarship",
    name: "Papua New Guinea Government Scholarships",
    level: ["bachelors", "masters"],
    award: "Scholarships funded by PNG government for eligible students for tertiary studies; covers full or partial tuition, possible allowances for living; details depend on scheme and institution.",
    website: "https://www.education.gov.pg/",  
    logo: null,
    countryName: "Papua New Guinea",
    countrySlug: "papua-new-guinea",
    lastUpdated: "2025-09-15",
  }
],


southkorea: [
  {
    id: "kr-gks-scholarship",
    name: "Global Korea Scholarship (GKS)",
    level: ["bachelors", "masters", "phd"],
    award: "Fully funded scholarship by the Korean government (via NIIED) for international students; covers tuition, airfare, monthly stipend, accommodation and medical insurance. ",  
    website: "https://www.studyinkorea.go.kr/en/plan/scholarships/gks.jsp",  
    logo: null,
    countryName: "South Korea",
    countrySlug: "south-korea",
    lastUpdated: "2025-09-15",
  },
  {
    id: "kr-univ-scholarships-universities",
    name: "University Scholarships at Leading Institutions (e.g. KAIST, POSTECH, Seoul National University)",
    level: ["masters", "phd"],
    award: "Merit-based scholarships/offers from top Korean universities for international students including tuition waiver + living stipend / research support.",  
    website: "https://oia.snu.ac.kr/",  // SNU’s international office site  
    logo: null,
    countryName: "South Korea",
    countrySlug: "south-korea",
    lastUpdated: "2025-09-15",
  }
],

unitedstates: [
  {
    id: "us-fulbright-foreign-student",
    name: "Fulbright Foreign Student Program (USA)",
    level: ["masters", "phd"],
    award: "Fully funded scholarships for graduate level international students; includes tuition, stipend, travel, health insurance etc.",  
    website: "https://foreign.fulbrightonline.org/",  
    logo: null,
    countryName: "United States",
    countrySlug: "united-states",
    lastUpdated: "2025-09-15",
  },
  {
    id: "us-hubert-humphrey-fellowship",
    name: "Hubert H. Humphrey Fellowship",
    level: ["professional / non-degree"], 
    award: "Non-degree fellowship for mid-career professionals to enhance leadership through study and professional experience in the U.S.",  
    website: "https://fulbrightprogram.org/us-humphrey-fellowship",  // check correct site  
    logo: null,
    countryName: "United States",
    countrySlug: "united-states",
    lastUpdated: "2025-09-15",
  },
  {
    id: "us-youarewelcomehere",
    name: "#YouAreWelcomeHere International Scholarships",
    level: ["bachelors", "masters", "exchange"],
    award: "Merit-based scholarships available at many US colleges participating in the #YouAreWelcomeHere network for international students.",  
    website: "https://youarewelcomehere.org/",  
    logo: null,
    countryName: "United States",
    countrySlug: "united-states",
    lastUpdated: "2025-09-15",
  }
],

unitedArabEmirates: [
  {
    id: "ae-moe-scholarships",
    name: "UAE Ministry of Education Scholarships for International Students",
    level: ["bachelors", "masters"],
    award: "Scholarships offered by the UAE government / Ministry of Education to attract foreign students to UAE universities; generally include tuition waiver, sometimes housing or stipend depending on university.",  
    website: "https://www.moe.gov.ae/",  
    logo: null,
    countryName: "United Arab Emirates",
    countrySlug: "united-arab-emirates",
    lastUpdated: "2025-09-15",
  },
  {
    id: "ae-uaeu-scholarships",
    name: "United Arab Emirates University Scholarships for Foreign Students",
    level: ["bachelors", "masters", "phd"],
    award: "Merit based scholarships for international students at UAEU; may include tuition discount/waiver and some support for fees or living stipend.",  
    website: "https://www.uaeu.ac.ae/",  
    logo: null,
    countryName: "United Arab Emirates",
    countrySlug: "united-arab-emirates",
    lastUpdated: "2025-09-15",
  }
],

vietnam: [
  {
    id: "vn-gov-scholarships",
    name: "Vietnam Government Scholarships (MOET / International Cooperation)",
    level: ["masters", "phd"],
    award: "Scholarships through Vietnamese government / education bodies for foreign students in Vietnam or Vietnamese students abroad, including tuition and sometimes stipend.",  
    website: "https://moet.gov.vn/",  
    logo: null,
    countryName: "Vietnam",
    countrySlug: "vietnam",
    lastUpdated: "2025-09-15",
  }
],

sweden: [
  {
    id: "se-swedish-institute-scholarships",
    name: "Swedish Institute Scholarships for Global Professionals",
    level: ["masters"],
    award: "High profile scholarship by Swedish Institute to support international master’s students from selected countries; includes tuition, living stipend, travel etc.",  
    website: "https://si.se/en/apply/scholarships/",  
    logo: null,
    countryName: "Sweden",
    countrySlug: "sweden",
    lastUpdated: "2025-09-15",
  }
],

taiwan: [
  {
    id: "tw-taiwan-scholarship",
    name: "Taiwan Government Scholarships for International Students",
    level: ["bachelors", "masters", "phd"],
    award: "Scholarships from MOE or other Taiwan government bodies to attract international students; includes tuition and sometimes lodging or stipend.",  
    website: "https://www.studyintaiwan.org/",  
    logo: null,
    countryName: "Taiwan",
    countrySlug: "taiwan",
    lastUpdated: "2025-09-15",
  }
],

thailand: [
  {
    id: "th-royal-thai-government-scholarships",
    name: "Royal Thai Government Scholarships",
    level: ["bachelors", "masters", "phd"],
    award: "Scholarships offered by the Thai government for international students for selected fields and universities; often include tuition, stipend or cost of living support.",  
    website: "https://www.mfa.go.th/en/page/scholarship",  
    logo: null,
    countryName: "Thailand",
    countrySlug: "thailand",
    lastUpdated: "2025-09-15",
  }
],

southAfrica: [
  {
    id: "za-mandela-rhodes",
    name: "Rhodes Scholarships (for South Africa & Southern Africa)",
    level: ["masters", "phd"],
    award: "Prestigious postgraduate scholarships to attend University of Oxford; covers tuition, stipend, travel, etc.",  
    website: "https://www.rhodeshouse.ox.ac.uk/scholarships/the-southern-africa/south-africa/",  
    logo: null,
    countryName: "South Africa",
    countrySlug: "south-africa",
    lastUpdated: "2025-09-15",
  },
  {
    id: "za-saica-university-student-development",
    name: "SAICA University Student Development Program Scholarships",
    level: ["professional / postgraduate"],
    award: "Scholarships / financial assistance for students pursuing accounting / finance professional qualifications, often in South Africa, through SAICA’s development initiatives.",  
    website: "https://www.saica.co.za",  
    logo: null,
    countryName: "South Africa",
    countrySlug: "south-africa",
    lastUpdated: "2025-09-15",
  }
],


 
};


export function getScholarshipsByCountry(slug) {
  return scholarshipsByCountry[slug] || [];
}
