import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/Navbar";

import { Poppins } from 'next/font/google';
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"], // required
  weight: ["400", "500", "700"], // choose font weights
  variable: "--font-roboto", // optional CSS variable
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata = {
  title: "Visa Era",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
